server:
  port: 7091

  
spring:
  application:
    name: gateway
  profiles:
    active: dev

  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:7071}"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
        max-attempts: 12

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:7081/eureka/}
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:serviya}
